name: Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
permissions:
  id-token: write
  contents: read

defaults: 
  run:
    shell: bash
    working-directory: ./

jobs: 
  deploy_production:
    name: 'Deploy to production'
    runs-on: ubuntu-latest
    env: 
      IMAGE_TAG: ${{ format('{0}_{1}', github.event.repository.name, github.sha ) }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ vars.envkey_PORT }}
          envkey_DB_HOST: ${{ vars.envkey_DB_HOST }}
          envkey_DB_USERNAME: ${{ vars.envkey_DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.envkey_DB_PASSWORD }}
          envkey_PG_DATABASE: ${{ vars.envkey_PG_DATABASE }}
          envkey_PG_PORT: ${{ vars.envkey_PG_PORT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::064299454727:role/energym-oidc-role
          role-session-name: energym_oidc_deployment
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        id: push-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: energym
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG